# Whiteflag datastores configuration file
#
# This configuration file contains datastore related configuration parameters
# Please see `./docs/configuration.md` for a description.
#

[[databases]]
name = "embedded-db"
module = "embeddb"
active = true
primary = true
directory = "/var/lib/whiteflag"
rxStoreEvent = ["messageProcessed", "messageUpdated"]
txStoreEvent = ["messageProcessed", "messageUpdated"]

[[databases]]
name = "mongodb"
module = "mongodb"
active = false
primary = false
dbProtocol = "mongodb"
dbHost = "localhost"
dbPort = "27017"
username = ""
password = ""
database = "whiteflag"
rxStoreEvent = ["messageProcessed", "messageUpdated"]
txStoreEvent = ["messageProcessed", "messageUpdated"]

[[databases]]
name = "rest-db"
module = "rest"
active = false
primary = false
dbProtocol = "https"
dbHost = ""
dbPort = ""
dbPath = "/whiteflag/services/wfapi.xsjs"
username = ""
password = ""
rxStoreEvent = ["messageProcessed", "messageUpdated"]
txStoreEvent = ["messageProcessed", "messageUpdated"]
